### ISSUE TITLE
4750

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/THEO-DOI-THUC-HIEN#3]
- [ ] - [x] dh-hos/Yeu_cau_ho_tro#156
- [x] dh-hos/To_Lap_Trinh#421
- [x] dh-hos/To_Trien_Khai#64
- [x] dh-hos/To_Lap_Trinh#423
- [x] dh-hos/To_Lap_Trinh/issues/424
- [x] dh-hos/To_Lap_Trinh#425
- [x] dh-hos/To_Lap_Trinh#426
- [x] https://github.com/dh-hos/Yeu_cau_ho_tro/issues/157
- [x] dh-hos/THEO-DOI-THUC-HIEN-4750#16
- [x] dh-hos/To_Lap_Trinh#427
- [x] https://github.com/dh-hos/dhg.hospitaladmin/issues/69
- [x] dh-hos/To_Lap_Trinh#429
- [x] dh-hos/To_Lap_Trinh#430
- [x] dh-hos/To_Lap_Trinh#431
- [x] dh-hos/To_Lap_Trinh#432
- [x] dh-hos/To_Lap_Trinh#433
- [x] dh-hos/To_Ho_Tro#37
- [x] dh-hos/To_Lap_Trinh#435
- [x] dh-hos/To_Lap_Trinh#436
- [x] dh-hos/To_Lap_Trinh#437
- [x] dh-hos/To_Lap_Trinh#438
- [x] dh-hos/THEO-DOI-THUC-HIEN-4750#30
- [x] dh-hos/To_Lap_Trinh#439
- [x] dh-hos/THEO-DOI-THUC-HIEN-4750#32
- [x] dh-hos/To_Trien_Khai#68
- [x] dh-hos/THEO-DOI-THUC-HIEN-4750#34
- [x] dh-hos/THEO-DOI-THUC-HIEN-4750#35
- [ ] dh-hos/To_Trien_Khai#69
- [ ] dh-hos/To_Ho_Tro#38
- [x] dh-hos/Yeu_cau_ho_tro#163
- [x] dh-hos/To_Lap_Trinh#445
- [x] dh-hos/To_Lap_Trinh#448
- [x] dh-hos/To_Lap_Trinh#449
- [ ] dh-hos/To_Lap_Trinh#450
- [x] https://github.com/dh-hos/dhg.hospitaladmin/issues/71
- [ ] dh-hos/To_Ho_Tro#75 
- [x] https://github.com/dh-hos/dhg.hosptaltreatment/issues/234
- [x] https://github.com/dh-hos/dhg.hospitalprescription/issues/268
- [x] https://github.com/dh-hos/To_Lap_Trinh/issues/451
- [x] dh-hos/To_Lap_Trinh#452
- [x] dh-hos/To_Lap_Trinh#456
- [x] https://github.com/dh-hos/dhg.hosptaltreatment/issues/240
- [x] dh-hos/To_Lap_Trinh#464
- [x] dh-hos/THEO-DOI-THUC-HIEN-4750#54
- [ ] dh-hos/To_Lap_Trinh#465
- [ ] https://github.com/dh-hos/To_Lap_Trinh/issues/466
- [x] dh-hos/To_Lap_Trinh#468
- [x] dh-hos/To_Lap_Trinh#469
- [x] https://github.com/dh-hos/To_Lap_Trinh/issues/471
- [x] dh-hos/To_Lap_Trinh#472
- [ ] dh-hos/To_Lap_Trinh#608
- [x] dh-hos/To_Lap_Trinh#477
- [x] dh-hos/To_Lap_Trinh#478
- [x] https://github.com/dh-hos/dhg.hospitaladmin/issues/76
- [x] dh-hos/To_Lap_Trinh#487
- [ ] dh-hos/THEO-DOI-THUC-HIEN-4750#67
- [x] dh-hos/To_Lap_Trinh#488
- [x] dh-hos/To_Lap_Trinh#490
- [x] dh-hos/To_Lap_Trinh#491
- [x] dh-hos/To_Lap_Trinh#492
- [x] https://github.com/dh-hos/To_Lap_Trinh/issues/493
- [x] https://github.com/dh-hos/To_Lap_Trinh/issues/494
- [x] https://github.com/dh-hos/To_Lap_Trinh/issues/495
- [x] dh-hos/To_Lap_Trinh#496
- [x] dh-hos/To_Lap_Trinh#499
- [x] dh-hos/To_Lap_Trinh#500
- [ ] dh-hos/To_Lap_Trinh#501
- [x] https://github.com/dh-hos/To_Lap_Trinh/issues/504
- [x] https://github.com/dh-hos/To_Lap_Trinh/issues/507
- [ ] https://github.com/dh-hos/To_Lap_Trinh/issues/508
- [x] https://github.com/dh-hos/To_Lap_Trinh/issues/509
- [x] dh-hos/To_Lap_Trinh#510
- [ ] dh-hos/To_Lap_Trinh#516
- [x] https://github.com/dh-hos/To_Lap_Trinh/issues/514
- [ ] dh-hos/To_Lap_Trinh#519
- [ ] dh-hos/To_Ho_Tro#51
- [ ] dh-hos/To_Lap_Trinh#523
- [x] https://github.com/dh-hos/Yeu_cau_ho_tro/issues/199
- [ ] https://github.com/dh-hos/Yeu_cau_ho_tro/issues/198#issuecomment-2244873737
- [x] dh-hos/THEO-DOI-THUC-HIEN-4750#83
- [x] dh-hos/To_Lap_Trinh#525
- [x] dh-hos/To_Lap_Trinh#530
- [x] https://github.com/dh-hos/To_Lap_Trinh/issues/531
- [ ] https://github.com/dh-hos/dhg.hospitalprescription/issues/285
- [x] dh-hos/To_Lap_Trinh#535
- [x] dh-hos/To_Lap_Trinh#542
- [x] dh-hos/To_Lap_Trinh#543
- [ ] dh-hos/To_Ho_Tro#50
- [x] dh-hos/To_Lap_Trinh#546
- [x] https://github.com/dh-hos/To_Lap_Trinh/issues/548
- [x] dh-hos/To_Lap_Trinh#549
- [x] https://github.com/dh-hos/To_Lap_Trinh/issues/552
- [x] dh-hos/To_Lap_Trinh#553
- [ ] dh-hos/To_Lap_Trinh#554
- [x] dh-hos/To_Lap_Trinh#567
- [ ] dh-hos/To_Lap_Trinh#572
- [ ] dh-hos/To_Lap_Trinh#586
- [ ] https://github.com/dh-hos/To_Lap_Trinh/issues/587
- [ ] dh-hos/To_Lap_Trinh#588
- [x] https://github.com/dh-hos/dhg.hospitaladmin/issues/88
- [ ] dh-hos/To_Lap_Trinh#589
- [ ] dh-hos/To_Lap_Trinh#105
- [ ] dh-hos/To_Lap_Trinh#106
- [ ] dh-hos/To_Lap_Trinh#594
- [ ] https://github.com/dh-hos/To_Lap_Trinh/issues/599
- [ ] https://github.com/dh-hos/To_Lap_Trinh/issues/602
- [ ] dh-hos/To_Lap_Trinh#110
- [ ] https://github.com/dh-hos/Yeu_cau_ho_tro/issues/258
- [ ] dh-hos/To_Lap_Trinh#607
- [x] dh-hos/To_Lap_Trinh#609
- [x] dh-hos/THEO-DOI-THUC-HIEN#113
- [ ] dh-hos/To_Lap_Trinh#617
- [ ] dh-hos/To_Lap_Trinh#621
- [ ] https://github.com/dh-hos/Yeu_cau_ho_tro/issues/266
- [x] dh-hos/To_Lap_Trinh#402
- [ ] dh-hos/To_Lap_Trinh#409
- [x] dh-hos/To_Lap_Trinh#413
- [ ] https://github.com/dh-hos/Yeu_cau_ho_tro/issues/283
- [x] dh-hos/Yeu_cau_ho_tro#121
- [x] #122
- [ ] https://github.com/dh-hos/Yeu_cau_ho_tro/issues/287
- [ ] dh-hos/Yeu_cau_ho_tro#125
- [ ] dh-hos/Yeu_cau_ho_tro#126
- [ ] https://github.com/dh-hos/To_Lap_Trinh/issues/644
- [x] #127
- [ ] https://github.com/dh-hos/Yeu_cau_ho_tro/issues/295
- [x] dh-hos/To_Ho_Tro#28
- [x] dh-hos/To_Ho_Tro#29
- [x] dh-hos/To_Trien_Khai#58
- [ ] https://github.com/dh-hos/To_Lap_Trinh/issues/661
- [ ] https://github.com/dh-hos/Yeu_cau_ho_tro/issues/319

**Comment by le-an-87** [comment]
Người tạo: Lê Hoàng ÂN
- [ ]

**Comment by le-an-87** [comment]
- [ ] Yêu cầu giá trị mặc định đối với XML 4750

**Comment by nghivanbi** [comment]
### 👌 ĐỒNG Ý THỰC HIỆN 👌
---------------------------------------------------------------------
👉 **Phân công thực hiện**: @ongtrieuhau, @lqbinh1987, @le-an-87 
📘 **Nội dung**:
Hủy theo dõi mục này theo biên bản họp 30/09/2024, các trường hợp YC, Lỗi còn tồn động và phát sinh thực hiện theo dõi theo qui trình xử lý công việc .
