### ISSUE TITLE
BB HỌP NHÓM (27/06/2024)

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/THEO-DOI-THUC-HIEN#38]
- [x] dh-hos/THEO-DOI-THUC-HIEN#39
- [x] [Report hỗ trợ gởi XML3.MA_BENH](https://github.com/dh-hos/To_Ho_Tro/issues/39)
- [x] dh-hos/To_Ho_Tro#58
